# https://docs.github.com/en/actions/sharing-automations/creating-actions/creating-a-docker-container-action
# https://github.com/athul/waka-readme/blob/master/action.yml
name: "Dirtree-to-Readme"
author: "qte77"
description: " Copy directory tree into Readme."
inputs:
  GH_TOKEN:
    default: ${{ github.token }}
    required: true
  REPOSITORY:
    default: ${{ github.repository }}
    required: false
  COMMITTER_NAME:
    default: "NOT_SET"
    required: false
  COMMITTER_EMAIL:
    default: "NOT_SET"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: "file-text"
  color: "white"

