---
name: Write drectory tree to README.md
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  OUT_FILE: data/dummy-dirtree.md
  # OUT_FILE: README.md
  COMMAND: "ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//──/g' -e 's/─/├/' -e '$s/├/└/'"
jobs:
  updateArxivCsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      #  with:
      #    sparse-checkout: $OUT_FILE
      #    sparse-checkout-cone-mode: false
      - name: Save directory tree to file
        run: |
          "This is a test file for dirtree to readme" > $OUT_FILE
          date -u +"%H:%M:%S %Z" >> $OUT_FILE
          ${{ env.COMMAND) >> $OUT_FILE
          echo >> $OUT_FILE
          $COMMAND >> $OUT_FILE
          echo >> $OUT_FILE
          $($COMMAND) >> $OUT_FILE
      - name: push updated csv file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $OUT_FILE
          git commit -m "Updated $OUT_FILE"
          git push origin main
...
