---
# https://github.com/lycheeverse/lychee-action
# https://github.com/marketplace/actions/lychee-broken-link-checker
name: "Link Checker"

on:
  workflow_dispatch:
  push:
    branches-ignore: [main]
  pull_request:
    types: [closed]
    branches: [main]
  schedule:
    - cron: "00 00 * * 0"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2

      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: lychee Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
...