---
# https://github.com/astral-sh/ruff-action
# https://github.com/astral-sh/ruff
name: ruff
on: 
  push:
  pull_request:
    types: [closed]
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
...