---
# https://github.com/chartboost/ruff-action
# https://github.com/astral-sh/ruff
name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
...
