---
name: 'test-dirtree-readme-action'
on: 
  # [push, pull_request]
  workflow_dispatch:
jobs:
  dirtree:
    runs-on: ubuntu-latest
    name: 'Get and save dirtree to README.md'
    steps:
      - name: checkout repo
        uses: actions/checkout@v4.2.2
        with:
          repository: pdq21/dev-dirtree-action-temp
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Call action
        uses: ./
...