---
name: Write directory tree to file, e.g. README.md
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  FILE_PATH: data
  FILE: dummy-dirtree.md
  COMMAND: $(ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//──/g' -e 's/─/├/' -e '$s/├/└/')
jobs:
  writeDirtreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OUT_FILE: $FILE_PATH/$FILE
    steps:
      - uses: actions/checkout@v4
      #  with:
      #    sparse-checkout: $OUT_FILE
      #    sparse-checkout-cone-mode: false
      - name: Save dirtree to file
        run: |
          if [[ ! -d "$FILE_PATH" ]]; then
            mkdir -p $FILE_PATH                      
          fi
          date -u +"%H:%M:%S %Z" > $OUT_FILE
          echo $COMMAND" >> $OUT_FILE
      - name: push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $OUT_FILE
          git commit -m "Updated $OUT_FILE"
          git push origin main
...
