---
name: Write directory tree to file, e.g. README.md
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  PATH: data
  FILE: dummy-dirtree.md
  #COMMAND: "ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//──/g' -e 's/─/├/' -e '$s/├/└/'"
jobs:
  writeDirtreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      #  with:
      #    sparse-checkout: $OUT_FILE
      #    sparse-checkout-cone-mode: false
      - name: Save dirtree to file
        run: |
          if [[ ! -d "$PATH" ]]; then
            mkdir -p $PATH                      
          fi
          date -u +"%H:%M:%S %Z" > $PATH/$FILE
          ls -R | grep ':$' | sed -e 's/:$//' -e 's/[^-][^\/]*\//──/g' -e 's/─/├/' -e '$s/├/└/' >> $PATH/$FILE
      - name: push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $PATH/$FILE
          git commit -m "Updated $PATH/$FILE"
          git push origin main
...
