---
name: write-dirtree-to-file

on:
  #schedule:
  # https://crontab.guru/every-day
  #- cron: "0 0 * * *"
  # pull_request:
  #  types: [closed]
  # push:
  #  branches: [main]
  workflow_dispatch:

env:
  # CMD_HIGHLIGHT: 'sh'
  # EXCLUDE: ''
  # INSERT_HERE_START_STRING: ''
  # INSERT_HERE_END_STRING: ''
  # OUT_FILE: 'README.md'
  # TREE_THEME: 'sh'
  APP: 'app/app.py'
  GH_EMAIL: 'dirtree@gha'
  GH_NAME: 'DirTreeToReadme-GHA'
  PY_VER: '3.12'

jobs:
  writeDirTreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set $OUT_FILE for action
        run: echo "OUT_FILE=${OUT_FILE:-README.md}" >> $GITHUB_ENV

      - name: Checkout full branch
        uses: actions/checkout@v4.2.2

      - name: Setup python '${{ env.PY_VER }}'
        uses: actions/setup-python@v5.3.0
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ${{ env.APP }}
        run: python ${{ env.APP }}

      - name: Check if there are any changes
        id: diff_check_changed
        run: |
          set +xe
          git add "${OUT_FILE}"
          git diff --cached --quiet && \
          	echo "No changes added. Nothing to do." || \
          	echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push '$OUT_FILE' if changed
        if: steps.diff_check_changed.outputs.changed == 'true'
        run: |
          git config --local user.email "${GH_EMAIL}"
          git config --local user.name "${GH_NAME}"
          git add "${OUT_FILE}"
          git commit -m "Updated '${OUT_FILE}'"
          git push

#      - name: Delete branch if PR is closed
#        if: github.event_name == 'pull_request' && github.event.action == 'closed'
#        uses: dawidd6/action-delete-branch@v3
#        with:
#          github_token: ${{ github.token }}
#          numbers: ${{ github.event.pull_request.number }}
...
