---
name: write-dirtree-to-file
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  FILE_PATH: data
  FILE: dummy-dirtree-python.md
jobs:
  writeDirtreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev-refactor-to-python
      #    sparse-checkout: ${{ env.OUT_FILE }}
      #    sparse-checkout-cone-mode: false
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#env
      # Variables in the env map cannot be defined in terms of other variables in the map.
      # or use 'GITHUB_ENV'
      - name: Set output file env variable
        run: |
          echo "OUT_FILE=${FILE_PATH}/${FILE}" >> $GITHUB_ENV
      - name: Save dirtree to file
        shell: python
        run: |
          import os
          k = 0
          exclude = ".git"
          with open("${{ env.OUT_FILE }}", 'a', encoding='UTF8') as f: # newline=''
            for dirname, dirnames, filenames in os.walk('.'):
              indent = " " * (k+1)
              indent_f = " " * (k+2)
              if exclude in dirnames:
                dirnames.remove(exclude)
              for subdirname in dirnames:
                dir = os.path.join(dirname, subdirname)
                f.write(indent + dir + u"\r\n")
              for filename in filenames:
                file = os.path.join(dirname, filename)
                f.write(indent_f + file + u"\r\n")
      - name: push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$OUT_FILE"
          git commit -m "Updated $OUT_FILE"
          git push
...
