---
name: write-dirtree-to-file
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  APP: 'app/app.py'
  GH_EMAIL: "action@github.com"
  GH_NAME: "GitHub Action"
  PY_VER: '3.10'
jobs:
  writeDirtreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout full branch
        uses: actions/checkout@v4
       # with:
       #   sparse-checkout: ${{ env.OUT_FILE }}             
      - name: Setup python ${{ env.PY_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
      - name: Run ${{ env.APP }}
        run: python ${{ env.APP }}
      - name: Check if there are any changes
        id: diff_check_changed
        run: |
          set +e
          git add $OUT_FILE
          git diff --cached --quiet && \
            echo "No changes added. Nothing to do." || \
            echo "changed=true" >> $GITHUB_OUTPUT
      - name: Commit and push if changes
        if: steps.diff_check_changed.outputs.changed == 'true'
        run: |
          git config --local user.email $GH_EMAIL
          git config --local user.name $GH_NAME
          git add "$OUT_FILE"
          git commit -m "Updated $OUT_FILE"
          git push
...
