---
name: write-dirtree-to-file
on:
  #schedule:
    # https://crontab.guru/every-day
    #- cron: "0 0 * * *"
  workflow_dispatch:
env:
  OUT_FILE: 'data/dummy-dirtree-python.md'
  EXCLUDE: '.git' # separated by |
  CMD_HIGHLIGHT: 'sh'
  PY_VER: '3.10'
jobs:
  writeDirtreeToFile:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout file sparse mode
        uses: actions/checkout@v4
        with:
          ref: dev-refactor-to-python
          sparse-checkout: ${{ env.OUT_FILE }}             
      - name: Setup python ${{ env.PY_VER }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
      - run: python app.py
      - name: Push updated file back to main branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "$OUT_FILE"
          git commit -m "Updated $OUT_FILE"
          git push
...
